### ISSUE TITLE
Provide healthcheck endpoint for an instance

### ISSUE THREAD

**Issue by nniehoff** [networktocode/ntc-netbox-plugin-metrics-ext#15]
### Environment
* Python version:  3.7.9
* NetBox version:  2.9.8
* ntc-netbox-plugin-metrics-ext version:  NA

### Proposed Functionality

NetBox itself does not provide a good health check endpoint for a load balancer to determine if NetBox is healthy or not.  For example if static files are not available connecting to http://netbox will return a 200 OK return code but there is javascript to redirect the client's browser to a static media failure page.  Programatically checking this endpoint validates but to the user NetBox is not available.  You could work around this by checking the content of the page but I can think of other examples such as a failure in redis or maybe something strange in django where this instance of NetBox is not healthy but it may return 200 for /.  The thought would be to create an endpoint to do some basic checks internally to NetBox, Django, Redis, Postgres, NGinx (static files) to return a more accurate health status.

### Use Case

Running NetBox in an HA environment it is necessary to understand the health of a single NetBox server to know if that instance is available for a load balancer to spread the load with.

**Comment by lampwins** [comment]
Take a look at https://github.com/netbox-community/netbox/issues/4918 which is intended to touch on this use case. Note it is exposed through the API, so authentication constraints exist, but it does expose info on rq workers. It will ship in 2.10

**Comment by nniehoff** [comment]
Closing this as I think it has been handled elsewhere.
